using System.Collections.Generic;

namespace CncSim.Core.Localization
{
    /// <summary>
    /// 内置中英文词条。键命名约定：code.* / desc.* / diag.* / explain.* / ui.* / unit.* / manual.*
    /// </summary>
    internal static class BuiltinStrings
    {
        public static void Register()
        {
            AddRange(Loc.Chinese, Zh);
            AddRange(Loc.English, En);
        }

        private static void AddRange(string lang, Dictionary<string, string> map)
        {
            foreach (var kv in map) Loc.Add(lang, kv.Key, kv.Value);
        }

        private static readonly Dictionary<string, string> Zh = new Dictionary<string, string>
        {
            // ---- 指令名称 code.* ----
            { "code.motion.rapid", "快速定位" },
            { "code.motion.linear", "直线插补" },
            { "code.motion.arc_cw", "顺时针圆弧插补" },
            { "code.motion.arc_ccw", "逆时针圆弧插补" },
            { "code.motion.dwell", "暂停延时" },
            { "code.g.canned_setup", "可编程数据输入" },
            { "code.plane.xy", "XY 平面选择" },
            { "code.plane.zx", "ZX 平面选择" },
            { "code.plane.yz", "YZ 平面选择" },
            { "code.units.inch", "英制单位" },
            { "code.units.mm", "公制单位" },
            { "code.g.return_home", "返回参考点" },
            { "code.g.return_home2", "返回第二参考点" },
            { "code.comp.cancel", "取消刀具半径补偿" },
            { "code.comp.left", "刀具半径左补偿" },
            { "code.comp.right", "刀具半径右补偿" },
            { "code.lencomp.positive", "刀具长度正补偿" },
            { "code.lencomp.cancel", "取消刀具长度补偿" },
            { "code.rtcp.on", "刀尖跟随(RTCP)" },
            { "code.scale.cancel", "取消缩放" },
            { "code.scale.on", "比例缩放" },
            { "code.offset.local", "局部坐标系" },
            { "code.offset.machine", "机床坐标系" },
            { "code.offset.g54", "工件坐标系 1" },
            { "code.offset.g55", "工件坐标系 2" },
            { "code.offset.g56", "工件坐标系 3" },
            { "code.offset.g57", "工件坐标系 4" },
            { "code.offset.g58", "工件坐标系 5" },
            { "code.offset.g59", "工件坐标系 6" },
            { "code.offset.g54_1", "附加工件坐标系" },
            { "code.g.exact_stop", "准确停止模式" },
            { "code.g.cont_path", "连续路径模式" },
            { "code.rotate.on", "坐标旋转" },
            { "code.rotate.cancel", "取消坐标旋转" },
            { "code.cycle.chip_break", "高速深孔断屑循环" },
            { "code.cycle.cancel", "取消固定循环" },
            { "code.cycle.drill", "钻孔循环" },
            { "code.cycle.drill_dwell", "钻孔暂停循环" },
            { "code.cycle.peck", "深孔啄钻循环" },
            { "code.cycle.tap", "刚性攻丝循环" },
            { "code.cycle.bore", "镗孔循环" },
            { "code.cycle.bore_back", "反镗孔循环" },
            { "code.cycle.bore_dwell", "镗孔暂停循环" },
            { "code.distance.absolute", "绝对编程" },
            { "code.distance.incremental", "增量编程" },
            { "code.arc_center.absolute", "圆弧中心绝对坐标" },
            { "code.arc_center.incremental", "圆弧中心增量坐标" },
            { "code.feed.inverse_time", "反比时间进给" },
            { "code.feed.per_minute", "每分钟进给" },
            { "code.feed.per_rev", "每转进给" },
            { "code.spindle.rpm", "恒转速控制" },
            { "code.spindle.css", "恒线速控制" },
            { "code.cycle.return_initial", "循环返回初始平面" },
            { "code.cycle.return_r", "循环返回 R 平面" },
            { "code.program.stop", "程序停止" },
            { "code.program.optional_stop", "可选程序停止" },
            { "code.program.end", "程序结束" },
            { "code.spindle.cw", "主轴正转" },
            { "code.spindle.ccw", "主轴反转" },
            { "code.spindle.stop", "主轴停止" },
            { "code.tool.change", "换刀" },
            { "code.coolant.mist", "雾状冷却开" },
            { "code.coolant.flood", "切削液开" },
            { "code.coolant.off", "冷却关" },
            { "code.program.end_rewind", "程序结束并复位" },
            { "code.sub.call", "调用子程序" },
            { "code.sub.return", "子程序返回" },

            // ---- 指令说明 desc.* ----
            { "desc.g00", "以机床最快速度移动到目标点，不进行切削。" },
            { "desc.g01", "以指定进给率 F 沿直线切削到目标点。" },
            { "desc.g02", "在选定平面内顺时针切削圆弧，用 I/J/K 或 R 指定圆弧。" },
            { "desc.g03", "在选定平面内逆时针切削圆弧，用 I/J/K 或 R 指定圆弧。" },
            { "desc.g04", "暂停指定时间，P 为毫秒，X 为秒（两种写法兼容）。" },
            { "desc.g10", "向控制器写入或修改刀具补偿、工件坐标系等数据。" },
            { "desc.g17", "选择 XY 平面进行圆弧插补与刀补。" },
            { "desc.g18", "选择 ZX 平面进行圆弧插补与刀补。" },
            { "desc.g19", "选择 YZ 平面进行圆弧插补与刀补。" },
            { "desc.g20", "后续尺寸按英寸解释，坐标与进给均为英制。" },
            { "desc.g21", "后续尺寸按毫米解释（默认）。" },
            { "desc.g28", "经中间点快速返回机床参考点。" },
            { "desc.g30", "经中间点返回第二参考点。" },
            { "desc.g40", "取消刀具半径补偿。" },
            { "desc.g41", "沿前进方向左侧进行刀具半径补偿，D 指定补偿号。" },
            { "desc.g42", "沿前进方向右侧进行刀具半径补偿，D 指定补偿号。" },
            { "desc.g43", "刀具长度正补偿，H 指定补偿号。" },
            { "desc.g43_4", "五轴刀尖跟随，旋转轴运动时刀尖保持不动。" },
            { "desc.g49", "取消刀具长度补偿。" },
            { "desc.g50", "取消比例缩放。" },
            { "desc.g51", "按 P 指定的比例对坐标进行缩放。" },
            { "desc.g52", "在工件坐标系基础上叠加局部偏置。" },
            { "desc.g53", "临时使用机床坐标系（忽略工件坐标系）。" },
            { "desc.g54", "选择第 1 工件坐标系。" },
            { "desc.g55", "选择第 2 工件坐标系。" },
            { "desc.g56", "选择第 3 工件坐标系。" },
            { "desc.g57", "选择第 4 工件坐标系。" },
            { "desc.g58", "选择第 5 工件坐标系。" },
            { "desc.g59", "选择第 6 工件坐标系。" },
            { "desc.g54_1", "用 P 指定附加工件坐标系（G54.1 Pn）。" },
            { "desc.g61", "每个程序段结束时减速到停止，保证轮廓精度。" },
            { "desc.g64", "程序段之间平滑过渡，提刀率（默认）。" },
            { "desc.g68", "以指定中心和角度旋转坐标系（XY 平面）。" },
            { "desc.g69", "取消坐标旋转。" },
            { "desc.g73", "深孔加工，每次钻到 Q 深度后快速退回断屑。" },
            { "desc.g80", "取消所有固定循环。" },
            { "desc.g81", "普通钻孔循环，钻到 Z 深度后快速退回。" },
            { "desc.g82", "钻孔到底后暂停 P 毫秒再退回。" },
            { "desc.g83", "啄钻循环，每次切入 Q 深度后完全退回排屑。" },
            { "desc.g84", "刚性攻丝，进给率由转速与螺距决定。" },
            { "desc.g85", "镗孔循环，到底后以进给速度退回。" },
            { "desc.g86", "反镗循环，主轴在孔底定向后偏移退刀。" },
            { "desc.g89", "镗孔循环，到底后暂停再以进给速度退回。" },
            { "desc.g90", "坐标值为相对于工件原点的绝对值。" },
            { "desc.g91", "坐标值为相对于当前位置的增量值。" },
            { "desc.g90_1", "圆弧 I/J/K 使用绝对坐标。" },
            { "desc.g91_1", "圆弧 I/J/K 使用相对于起点的增量值（默认）。" },
            { "desc.g93", "进给率按反比时间给定，F 为 mm/分钟的运动时间倒数。" },
            { "desc.g94", "进给率单位为每分钟毫米（默认）。" },
            { "desc.g95", "进给率单位为每转毫米，与主轴转速联动。" },
            { "desc.g96", "主轴按指定转速（rpm）旋转。" },
            { "desc.g97", "主轴按恒线速度控制，随直径变化调整转速。" },
            { "desc.g98", "固定循环返回到初始平面。" },
            { "desc.g99", "固定循环返回到 R 平面。" },
            { "desc.m00", "程序无条件停止，需人工按启动继续。" },
            { "desc.m01", "可选停止，仅在可选停止开关打开时生效。" },
            { "desc.m02", "程序结束，主轴与冷却停止。" },
            { "desc.m03", "主轴正转，S 指定转速。" },
            { "desc.m04", "主轴反转。" },
            { "desc.m05", "主轴停止。" },
            { "desc.m06", "执行换刀，T 指定刀号。" },
            { "desc.m07", "开启雾状冷却。" },
            { "desc.m08", "开启切削液（ flood 冷却）。" },
            { "desc.m09", "关闭冷却。" },
            { "desc.m30", "程序结束并复位到程序头。" },
            { "desc.m98", "调用子程序，P 为子程序号，L 为次数。" },
            { "desc.m99", "从子程序返回主程序。" },

            // ---- 诊断 diag.* ----
            { "diag.unclosed_comment", "注释缺少右括号“)”" },
            { "diag.missing_value", "地址 {0} 缺少数值" },
            { "diag.invalid_number", "数值格式错误：“{0}”" },
            { "diag.unexpected_char", "无法识别的字符“{0}”" },
            { "diag.unknown_address", "未知地址字 {0}" },
            { "diag.unknown_g", "未知 G 指令 G{0}" },
            { "diag.unknown_m", "未知 M 指令 M{0}" },
            { "diag.arc_no_params", "圆弧指令缺少 I/J/K 或 R 参数" },
            { "diag.arc_missing_axis", "圆弧缺少平面内坐标（需 {0} 和 {1}）" },
            { "diag.arc_radius_invalid", "圆弧半径为 0 或无效" },
            { "diag.arc_radius_mismatch", "R 值与起终点计算半径不一致（误差 {0:0.###}mm）" },
            { "diag.arc_no_endpoint", "圆弧起点与终点重合且未指定整圆参数" },
            { "diag.feed_missing", "切削运动 G01/G02/G03 未指定进给率 F" },
            { "diag.feed_zero", "进给率 F 为 0" },
            { "diag.spindle_zero", "主轴转速 S 为 0 但仍执行切削" },
            { "diag.spindle_not_started", "切削前主轴未启动（缺少 M03/M04）" },
            { "diag.tool_missing", "使用了 T 指令但没有 M06 换刀" },
            { "diag.tool_out_of_library", "刀号 T{0} 不在刀具库中" },
            { "diag.diameter_exceeds_radius", "刀具直径 {0:0.###}mm 大于圆弧直径 {1:0.###}mm" },
            { "diag.modal_conflict", "同一程序段内出现互斥指令 {0} 与 {1}" },
            { "diag.cutter_comp_arc", "刀具半径补偿下的圆弧可能产生过切，请检查" },
            { "diag.rtcp_missing", "五轴旋转运动需开启 G43.4 刀尖跟随" },
            { "diag.soft_limit_x", "X 轴超程：{0:0.###} 超出行程 [{1:0.###}, {2:0.###}]" },
            { "diag.soft_limit_y", "Y 轴超程：{0:0.###} 超出行程 [{1:0.###}, {2:0.###}]" },
            { "diag.soft_limit_z", "Z 轴超程：{0:0.###} 超出行程 [{1:0.###}, {2:0.###}]" },
            { "diag.soft_limit_a", "A 轴超程：{0:0.###} 超出行程 [{1:0.###}, {2:0.###}]" },
            { "diag.soft_limit_b", "B 轴超程：{0:0.###} 超出行程 [{1:0.###}, {2:0.###}]" },
            { "diag.soft_limit_c", "C 轴超程：{0:0.###} 超出行程 [{1:0.###}, {2:0.###}]" },
            { "diag.outside_blank", "刀路超出毛坯范围，可能空切" },
            { "diag.overcut", "过切：切削深度超出毛坯底面 {0:0.###}mm" },
            { "diag.no_program_number", "缺少程序号 O 开头（部分控制器要求）" },
            { "diag.no_program_end", "程序缺少结束指令 M02/M30" },
            { "diag.canned_cycle_g80", "固定循环未用 G80 取消" },
            { "diag.duplicate_same_line", "同一程序段重复出现指令 {0}" },
            { "diag.zero_position_move", "运动目标与当前点重合，可删除该段" },
            { "diag.rapid_through_material", "快移可能穿过毛坯，存在碰撞风险" },
            { "diag.unknown_coordinate_system", "未选择工件坐标系（G54-G59）" },

            // ---- 单行解释 explain.* ----
            { "explain.empty", "空行 / 注释行" },
            { "explain.prefix_rapid", "快速移动到" },
            { "explain.prefix_linear", "直线切削到" },
            { "explain.prefix_arc_cw", "顺时针圆弧切削到" },
            { "explain.prefix_arc_ccw", "逆时针圆弧切削到" },
            { "explain.at_absolute", "（绝对坐标）" },
            { "explain.at_incremental", "（增量 {0}）" },
            { "explain.feed", "，进给率 {0:0.###}mm/min" },
            { "explain.feed_per_rev", "，每转进给 {0:0.###}mm/rev" },
            { "explain.radius", "，半径 {0:0.###}mm" },
            { "explain.plane", "，{0} 平面" },
            { "explain.dwell", "暂停 {0:0.###} 秒" },
            { "explain.spindle_on_cw", "主轴正转 {0:0} rpm" },
            { "explain.spindle_on_ccw", "主轴反转 {0:0} rpm" },
            { "explain.spindle_stop", "主轴停止" },
            { "explain.coolant_on", "开启冷却" },
            { "explain.coolant_off", "关闭冷却" },
            { "explain.tool_change", "换刀至 T{0}" },
            { "explain.tool_prepare", "预选刀具 T{0}" },
            { "explain.program_end", "程序结束" },
            { "explain.program_stop", "程序停止" },
            { "explain.optional_stop", "可选停止" },
            { "explain.cycle_enter", "进入固定循环 {0}" },
            { "explain.cycle_cancel", "取消固定循环" },
            { "explain.units", "单位切换为{0}" },
            { "explain.work_offset", "选择工件坐标系 {0}" },
            { "explain.rtcp_on", "开启刀尖跟随" },
            { "explain.rtcp_off", "关闭刀尖跟随" },
            { "explain.no_motion", "无运动" },

            // ---- 单位 / 其它 ----
            { "unit.mm", "毫米" },
            { "unit.inch", "英寸" },
            { "unit.mm_per_min", "毫米/分钟" },
            { "unit.mm_per_rev", "毫米/转" },
            { "unit.rpm", "转/分钟" },
            { "unit.second", "秒" },

            // ---- 速查手册分类 ----
            { "manual.category.motion", "运动指令" },
            { "manual.category.plane_units", "平面 / 单位 / 坐标方式" },
            { "manual.category.compensation", "刀具补偿" },
            { "manual.category.coordinates", "坐标系与变换" },
            { "manual.category.feed_spindle", "进给与主轴" },
            { "manual.category.cycles", "固定循环" },
            { "manual.category.other_g", "其它 G 指令" },
            { "manual.category.misc_m", "M 辅助功能" },

            // ---- UI 文案（供界面层使用） ----
            { "ui.menu.file", "文件" },
            { "ui.menu.new", "新建" },
            { "ui.menu.open", "打开" },
            { "ui.menu.save", "保存" },
            { "ui.menu.save_as", "另存为" },
            { "ui.menu.import", "导入" },
            { "ui.menu.export", "导出" },
            { "ui.menu.share", "分享" },
            { "ui.menu.recent", "最近文件" },
            { "ui.menu.undo", "撤销" },
            { "ui.menu.redo", "重做" },
            { "ui.menu.find", "查找" },
            { "ui.menu.replace", "替换" },
            { "ui.menu.simulate", "仿真" },
            { "ui.tab.simulation", "仿真" },
            { "ui.tab.tools", "刀具" },
            { "ui.tab.blank", "毛坯" },
            { "ui.tab.manual", "速查手册" },
            { "ui.view.top", "俯视" },
            { "ui.view.front", "前视" },
            { "ui.view.side", "侧视" },
            { "ui.view.iso", "等轴测" },
            { "ui.blank.box", "长方体" },
            { "ui.blank.cylinder", "圆柱" },
            { "ui.blank.custom", "自定义" },
            { "ui.tool.flat", "平底刀" },
            { "ui.tool.ball", "球头刀" },
            { "ui.tool.bull", "圆鼻刀" },
            { "ui.tool.drill", "麻花钻" },
            { "ui.tool.tap", "丝锥" },
            { "ui.tool.chamfer", "倒角刀" },
            { "ui.tool.thread", "螺纹刀" },
            { "ui.tool.probe", "测头" },
            { "ui.machine.3axis", "三轴立式" },
            { "ui.machine.4axis", "四轴" },
            { "ui.machine.5axis", "五轴" },
            { "ui.scene.trajectory", "刀具轨迹" },
            { "ui.scene.machine", "机床" },
            { "ui.scene.workpiece", "工件" },
            { "ui.scene.fixture", "夹具" },
            { "ui.scene.axes", "坐标系" },
            { "ui.scene.grid", "网格" },
            { "ui.scene.section", "截面" },
            { "ui.theme.dark", "暗色主题" },
            { "ui.theme.light", "亮色主题" },

            // ---- 路径优化建议 ----
            { "opt.redundant_rapid", "存在零位移的快速移动，可删除以缩短空行程" },
            { "opt.feed_variation", "进给率在 {0:0.###} 到 {1:0.###}mm/min 之间变化（{2:0.##}倍），建议统一以保护刀具" },
            { "opt.deep_plunge", "检测到深孔垂直下刀，建议先用钻头引孔或分层下刀" },
            { "opt.rapid_low", "快移在低 Z 高度进行，存在撞料风险，建议提高安全平面" },
            { "opt.tool_order", "刀具调用顺序存在 {0} 次重复换刀，建议合并同刀工序" },
            { "opt.back_forth", "存在往复空行程，可优化路径顺序" },

            // ---- 碰撞 ----
            { "collision.toolworkpiece", "第 {0} 行：刀具与工件碰撞（深度 {1:0.###}mm）" },
            { "collision.toolfixture", "第 {0} 行：刀具与夹具碰撞（深度 {1:0.###}mm）" },
            { "collision.toolmachine", "第 {0} 行：刀具与机床碰撞（深度 {1:0.###}mm）" },
            { "collision.holderworkpiece", "第 {0} 行：刀柄与工件碰撞（深度 {1:0.###}mm）" },
            { "collision.holderfixture", "第 {0} 行：刀柄与夹具碰撞（深度 {1:0.###}mm）" },
            { "collision.holdermachine", "第 {0} 行：刀柄与机床碰撞（深度 {1:0.###}mm）" },
            { "collision.rapidthroughmaterial", "第 {0} 行：快速移动穿过毛坯" },

            // ---- 材料 ----
            { "material.aluminum", "铝合金" },
            { "material.steel_1045", "45# 钢" },
            { "material.stainless_304", "304 不锈钢" },
            { "material.brass", "黄铜" },
            { "material.copper", "紫铜" },
            { "material.cast_iron", "铸铁" },
            { "material.titanium", "钛合金" },
            { "material.plastic_abs", "ABS 塑料" },
            { "material.wood", "木材" },

            // ---- 录制/回放/导入/项目 ui.* ----
            { "ui.record.start", "开始录制" },
            { "ui.record.stop", "停止录制" },
            { "ui.record.replay", "回放" },
            { "ui.record.pause", "暂停回放" },
            { "ui.record.save", "保存录制" },
            { "ui.record.load", "加载录制" },
            { "ui.import.model", "导入模型" },
            { "ui.import.stl", "导入 STL 模型" },
            { "ui.import.step", "导入 STEP 模型" },
            { "ui.import.gltf_fbx", "导入 glTF/FBX 模型" },
            { "ui.import.machine_fixture", "导入机床/夹具模型" },
            { "ui.capture.screenshot", "截图保存" },
            { "ui.capture.video", "导出仿真视频" },
            { "ui.project.manager", "项目管理" },
            { "ui.project.new", "新建项目" },
            { "ui.project.duplicate", "复制项目" },
            { "ui.project.delete", "删除项目" },
            { "ui.project.rename", "重命名项目" },

            // ---- 主界面骨架 ----
            { "ui.app.title", "CNC 加工仿真" },
            { "ui.tab.file", "文件" },
            { "ui.tab.analysis", "分析" },
            { "ui.tab.scene", "场景" },
            { "ui.tab.media", "录制/媒体" },
            { "ui.tab.project", "项目" },
            { "ui.tab.tutorial", "教程" },
            { "ui.machine.custom", "自定义机床" },
            { "ui.view.fit", "适配视图" },
            { "ui.view.back", "后视" },
            { "ui.view.bottom", "底视" },
            { "ui.view.orbit_hint", "左键旋转 · 右键平移 · 滚轮缩放" },

            // ---- 播放控制 ----
            { "ui.ctrl.play", "播放/暂停" },
            { "ui.ctrl.stop", "停止" },
            { "ui.ctrl.step_fwd", "单步前进" },
            { "ui.ctrl.step_back", "单步后退" },
            { "ui.ctrl.restart", "从头开始" },
            { "ui.ctrl.speed", "速度" },
            { "ui.ctrl.progress", "进度" },

            // ---- 仿真状态 ----
            { "ui.status.idle", "就绪" },
            { "ui.status.running", "仿真中…" },
            { "ui.status.paused", "已暂停" },
            { "ui.status.stopped", "已停止" },
            { "ui.status.finished", "仿真完成" },
            { "ui.status.theme_toggled", "已切换主题" },
            { "ui.status.saved", "已保存" },
            { "ui.status.open_failed", "打开失败" },
            { "ui.status.no_program", "请先打开或输入 G 代码" },
            { "ui.status.recording", "录制中…" },
            { "ui.status.replaying", "回放中…" },

            // ---- 文件面板 ----
            { "ui.file.new", "新建" },
            { "ui.file.clear", "清空" },
            { "ui.file.recent", "最近文件" },
            { "ui.file.recover", "恢复的会话" },
            { "ui.file.export", "导出到文件…" },
            { "ui.file.font_size", "字号" },
            { "ui.file.wrap", "自动换行" },
            { "ui.file.diagnostics", "诊断" },

            // ---- 仿真面板 ----
            { "ui.sim.controls", "播放控制" },
            { "ui.sim.progress", "进度" },
            { "ui.sim.live_removal", "实时材料去除" },
            { "ui.sim.trajectory", "显示刀具轨迹" },
            { "ui.sim.rapid", "显示快移" },
            { "ui.sim.cutting", "显示切削" },
            { "ui.sim.style", "轨迹样式" },
            { "ui.sim.style.lines", "线框" },
            { "ui.sim.style.solid", "实体" },
            { "ui.sim.quality", "质量" },
            { "ui.sim.quality.low", "低" },
            { "ui.sim.quality.medium", "中" },
            { "ui.sim.quality.high", "高" },

            // ---- 刀具面板 ----
            { "ui.tools.list", "刀具列表" },
            { "ui.tools.add", "新增刀具" },
            { "ui.tools.remove", "删除" },
            { "ui.tools.type", "类型" },
            { "ui.tools.number", "刀号" },
            { "ui.tools.diameter", "直径 (mm)" },
            { "ui.tools.corner", "圆角半径 (mm)" },
            { "ui.tools.flute", "刃长 (mm)" },
            { "ui.tools.stickout", "伸出长度 (mm)" },
            { "ui.tools.selected", "当前刀具" },

            // ---- 毛坯面板 ----
            { "ui.blank.shape", "形状" },
            { "ui.blank.size_x", "X 尺寸 (mm)" },
            { "ui.blank.size_y", "Y 尺寸 (mm)" },
            { "ui.blank.size_z", "Z 尺寸 (mm)" },
            { "ui.blank.material", "材料" },
            { "ui.blank.offset", "工件坐标系" },
            { "ui.blank.fixture", "启用夹具" },
            { "ui.blank.touch", "三点对刀" },

            // ---- 分析面板 ----
            { "ui.analysis.run", "重新分析" },
            { "ui.analysis.time", "加工时间" },
            { "ui.analysis.collision", "碰撞检测" },
            { "ui.analysis.machining", "过切/欠切" },
            { "ui.analysis.optimize", "路径优化建议" },
            { "ui.analysis.params", "推荐切削参数" },
            { "ui.analysis.none", "无" },
            { "ui.analysis.runtime", "运行时间" },
            { "ui.analysis.total", "总计" },

            // ---- 场景面板 ----
            { "ui.scene.show_grid", "显示网格" },
            { "ui.scene.show_axes", "显示坐标轴" },
            { "ui.scene.show_machine", "显示机床" },
            { "ui.scene.show_workpiece", "显示工件" },
            { "ui.scene.show_fixture", "显示夹具" },
            { "ui.scene.section_enable", "启用截面" },
            { "ui.scene.section_axis", "截面轴" },
            { "ui.scene.section_offset", "截面位置" },
            { "ui.scene.opacity", "透明度" },
            { "ui.scene.measure", "测量工具" },
            { "ui.scene.measure.none", "关闭" },
            { "ui.scene.measure.distance", "距离" },
            { "ui.scene.measure.angle", "角度" },
            { "ui.scene.measure.clear", "清除测量" },

            // ---- 媒体/录制面板 ----
            { "ui.media.screenshot", "截图" },
            { "ui.media.video_record", "录像帧序列" },
            { "ui.media.video_stop", "停止录像" },
            { "ui.media.sim_start", "开始录制仿真" },
            { "ui.media.sim_stop", "停止录制仿真" },
            { "ui.media.sim_replay", "回放" },
            { "ui.media.sim_save", "保存录制" },
            { "ui.media.sim_load", "加载录制" },

            // ---- 代码编辑器 ----
            { "ui.editor.toggle", "代码编辑器" },
            { "ui.editor.shown", "已打开代码编辑器" },
            { "ui.editor.hidden", "已关闭代码编辑器" },
            { "ui.editor.placeholder", "选中一行后在此编辑" },
            { "ui.editor.apply", "应用" },

            // ---- 项目面板 ----
            { "ui.project.name", "项目名称" },
            { "ui.project.create", "新建项目" },
            { "ui.project.save", "保存到项目" },
            { "ui.project.load", "载入项目" },
            { "ui.project.empty", "暂无项目" },

            // ---- 教程面板 ----
            { "ui.tutorial.list", "教程列表" },
            { "ui.tutorial.start", "开始" },
            { "ui.tutorial.next", "下一步" },
            { "ui.tutorial.prev", "上一步" },
            { "ui.tutorial.finish", "完成" },

            // ---- 手册面板 ----
            { "ui.manual.search", "搜索 G/M 指令" },
            { "ui.manual.g", "G 指令" },
            { "ui.manual.m", "M 指令" },

            // ---- 导入诊断 diag.import.* ----
            { "diag.import.unsupported", "不支持的模型格式：{0}" },
            { "diag.import.requires_unity", "该格式需在 Unity 层导入（glTF/FBX/STEP）" },
            { "diag.import.failed", "模型导入失败：{0}" },

            // ---- 教程与帮助 tutorial.* ----
            { "tutorial.getting_started.title", "快速上手" },
            { "tutorial.getting_started.desc", "从打开程序到运行仿真的完整流程" },
            { "tutorial.gs.s1.title", "欢迎使用 CNC 仿真" },
            { "tutorial.gs.s1.body", "本教程将带你完成一次完整的加工仿真。点击“下一步”继续。" },
            { "tutorial.gs.s2.title", "打开 G 代码" },
            { "tutorial.gs.s2.body", "在代码编辑器中粘贴或打开一个 .nc / .tap 程序，语法错误会即时标出。" },
            { "tutorial.gs.s3.title", "试试打开文件" },
            { "tutorial.gs.s3.body", "点击“打开”按钮加载一个示例程序。" },
            { "tutorial.gs.s4.title", "运行仿真" },
            { "tutorial.gs.s4.body", "点击“仿真”按钮开始，观察刀具按程序逐段运动。" },
            { "tutorial.gs.s5.title", "查看结果" },
            { "tutorial.gs.s5.body", "在三维视图中旋转、缩放，检查加工后的工件形状。" },

            { "tutorial.simulation.title", "仿真与材料去除" },
            { "tutorial.simulation.desc", "设置刀具、毛坯并控制仿真播放" },
            { "tutorial.sim.s1.title", "选择刀具" },
            { "tutorial.sim.s1.body", "在刀具面板中选择刀具类型与直径，材料去除会使用其真实形状。" },
            { "tutorial.sim.s2.title", "定义毛坯" },
            { "tutorial.sim.s2.body", "设置毛坯尺寸与材料，切削参数估算会据此给出推荐值。" },
            { "tutorial.sim.s3.title", "播放控制" },
            { "tutorial.sim.s3.body", "使用播放、暂停、单步与拖动时间轴来逐段检查程序。" },
            { "tutorial.sim.s4.title", "调整速度" },
            { "tutorial.sim.s4.body", "拖动速度滑块可在不影响时间估算的前提下加快预览。" },
            { "tutorial.sim.s5.title", "时间轴" },
            { "tutorial.sim.s5.body", "时间轴显示快移与切削段的分布，可快速定位到任意时刻。" },

            { "tutorial.fiveaxis.title", "五轴仿真" },
            { "tutorial.fiveaxis.desc", "配置多轴机床与刀尖跟随" },
            { "tutorial.5x.s1.title", "选择机床" },
            { "tutorial.5x.s1.body", "在机床选择器中选择 4 轴或 5 轴配置。" },
            { "tutorial.5x.s2.title", "运动学结构" },
            { "tutorial.5x.s2.body", "机床支持 Table-Table、Head-Table 与 Head-Head 结构，会自动求解刀尖位置。" },
            { "tutorial.5x.s3.title", "启用 RTCP" },
            { "tutorial.5x.s3.body", "勾选 RTCP 后，编程坐标即为刀尖点坐标，系统自动补偿旋转。" },
        };

        private static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            { "code.motion.rapid", "Rapid positioning" },
            { "code.motion.linear", "Linear interpolation" },
            { "code.motion.arc_cw", "Circular interpolation CW" },
            { "code.motion.arc_ccw", "Circular interpolation CCW" },
            { "code.motion.dwell", "Dwell" },
            { "code.g.canned_setup", "Programmable data input" },
            { "code.plane.xy", "XY plane" },
            { "code.plane.zx", "ZX plane" },
            { "code.plane.yz", "YZ plane" },
            { "code.units.inch", "Inch units" },
            { "code.units.mm", "Metric units" },
            { "code.g.return_home", "Return to reference point" },
            { "code.g.return_home2", "Return to 2nd reference point" },
            { "code.comp.cancel", "Cutter compensation cancel" },
            { "code.comp.left", "Cutter compensation left" },
            { "code.comp.right", "Cutter compensation right" },
            { "code.lencomp.positive", "Tool length compensation +" },
            { "code.lencomp.cancel", "Tool length compensation cancel" },
            { "code.rtcp.on", "TCPM / RTCP on" },
            { "code.scale.cancel", "Scaling cancel" },
            { "code.scale.on", "Scaling" },
            { "code.offset.local", "Local coordinate system" },
            { "code.offset.machine", "Machine coordinate system" },
            { "code.offset.g54", "Work offset 1" },
            { "code.offset.g55", "Work offset 2" },
            { "code.offset.g56", "Work offset 3" },
            { "code.offset.g57", "Work offset 4" },
            { "code.offset.g58", "Work offset 5" },
            { "code.offset.g59", "Work offset 6" },
            { "code.offset.g54_1", "Additional work offset" },
            { "code.g.exact_stop", "Exact stop mode" },
            { "code.g.cont_path", "Continuous path mode" },
            { "code.rotate.on", "Coordinate rotation" },
            { "code.rotate.cancel", "Coordinate rotation cancel" },
            { "code.cycle.chip_break", "High speed peck drilling" },
            { "code.cycle.cancel", "Canned cycle cancel" },
            { "code.cycle.drill", "Drilling cycle" },
            { "code.cycle.drill_dwell", "Drilling cycle with dwell" },
            { "code.cycle.peck", "Peck drilling cycle" },
            { "code.cycle.tap", "Tapping cycle" },
            { "code.cycle.bore", "Boring cycle" },
            { "code.cycle.bore_back", "Back boring cycle" },
            { "code.cycle.bore_dwell", "Boring cycle with dwell" },
            { "code.distance.absolute", "Absolute programming" },
            { "code.distance.incremental", "Incremental programming" },
            { "code.arc_center.absolute", "Arc center absolute" },
            { "code.arc_center.incremental", "Arc center incremental" },
            { "code.feed.inverse_time", "Inverse time feed" },
            { "code.feed.per_minute", "Feed per minute" },
            { "code.feed.per_rev", "Feed per revolution" },
            { "code.spindle.rpm", "Constant spindle speed" },
            { "code.spindle.css", "Constant surface speed" },
            { "code.cycle.return_initial", "Return to initial plane" },
            { "code.cycle.return_r", "Return to R plane" },
            { "code.program.stop", "Program stop" },
            { "code.program.optional_stop", "Optional stop" },
            { "code.program.end", "Program end" },
            { "code.spindle.cw", "Spindle CW" },
            { "code.spindle.ccw", "Spindle CCW" },
            { "code.spindle.stop", "Spindle stop" },
            { "code.tool.change", "Tool change" },
            { "code.coolant.mist", "Mist coolant on" },
            { "code.coolant.flood", "Flood coolant on" },
            { "code.coolant.off", "Coolant off" },
            { "code.program.end_rewind", "Program end and rewind" },
            { "code.sub.call", "Subprogram call" },
            { "code.sub.return", "Subprogram return" },

            { "desc.g00", "Move rapidly to the target point without cutting." },
            { "desc.g01", "Cut in a straight line to the target at feed rate F." },
            { "desc.g02", "Cut a clockwise arc in the selected plane using I/J/K or R." },
            { "desc.g03", "Cut a counter-clockwise arc in the selected plane." },
            { "desc.g04", "Pause for the given time. P is milliseconds, X is seconds." },
            { "desc.g10", "Write or modify controller data such as offsets." },
            { "desc.g17", "Select the XY plane for arcs and cutter compensation." },
            { "desc.g18", "Select the ZX plane." },
            { "desc.g19", "Select the YZ plane." },
            { "desc.g20", "Interpret dimensions in inches." },
            { "desc.g21", "Interpret dimensions in millimetres (default)." },
            { "desc.g28", "Rapid return to machine reference through an intermediate point." },
            { "desc.g30", "Return to the second reference point." },
            { "desc.g40", "Cancel cutter radius compensation." },
            { "desc.g41", "Cutter compensation to the left of the path; D selects the offset." },
            { "desc.g42", "Cutter compensation to the right of the path." },
            { "desc.g43", "Positive tool length compensation; H selects the offset." },
            { "desc.g43_4", "Five-axis tool tip following; the tip stays fixed when rotary axes move." },
            { "desc.g49", "Cancel tool length compensation." },
            { "desc.g50", "Cancel scaling." },
            { "desc.g51", "Scale coordinates by the factor given in P." },
            { "desc.g52", "Apply a local offset on top of the work offset." },
            { "desc.g53", "Temporarily use the machine coordinate system." },
            { "desc.g54", "Select work offset 1." },
            { "desc.g55", "Select work offset 2." },
            { "desc.g56", "Select work offset 3." },
            { "desc.g57", "Select work offset 4." },
            { "desc.g58", "Select work offset 5." },
            { "desc.g59", "Select work offset 6." },
            { "desc.g54_1", "Additional work offset selected with P." },
            { "desc.g61", "Decelerate to a stop at the end of each block." },
            { "desc.g64", "Smooth transition between blocks (default)." },
            { "desc.g68", "Rotate the coordinate system around the given centre." },
            { "desc.g69", "Cancel coordinate rotation." },
            { "desc.g73", "Deep hole drilling; retract quickly after each peck of depth Q." },
            { "desc.g80", "Cancel all canned cycles." },
            { "desc.g81", "Standard drilling cycle; rapid retract from the depth." },
            { "desc.g82", "Drilling with a dwell of P milliseconds at the bottom." },
            { "desc.g83", "Peck drilling; fully retract after each peck for chip clearing." },
            { "desc.g84", "Rigid tapping; feed is derived from speed and pitch." },
            { "desc.g85", "Boring cycle; retract at feed rate." },
            { "desc.g86", "Back boring cycle; orient, offset and retract." },
            { "desc.g89", "Boring cycle with dwell before retracting at feed rate." },
            { "desc.g90", "Coordinates are absolute from the work origin." },
            { "desc.g91", "Coordinates are incremental from the current position." },
            { "desc.g90_1", "Arc I/J/K are absolute coordinates." },
            { "desc.g91_1", "Arc I/J/K are incremental from the start point (default)." },
            { "desc.g93", "Inverse time feed; F is the reciprocal of the motion time in minutes." },
            { "desc.g94", "Feed rate in millimetres per minute (default)." },
            { "desc.g95", "Feed rate in millimetres per revolution." },
            { "desc.g96", "Spindle runs at the given rpm." },
            { "desc.g97", "Constant surface speed control." },
            { "desc.g98", "Canned cycle returns to the initial plane." },
            { "desc.g99", "Canned cycle returns to the R plane." },
            { "desc.m00", "Unconditional program stop." },
            { "desc.m01", "Optional stop, active only when the switch is enabled." },
            { "desc.m02", "Program end; spindle and coolant stop." },
            { "desc.m03", "Spindle clockwise at speed S." },
            { "desc.m04", "Spindle counter-clockwise." },
            { "desc.m05", "Spindle stop." },
            { "desc.m06", "Tool change to the tool in T." },
            { "desc.m07", "Mist coolant on." },
            { "desc.m08", "Flood coolant on." },
            { "desc.m09", "Coolant off." },
            { "desc.m30", "Program end and rewind to the start." },
            { "desc.m98", "Call subprogram P, L times." },
            { "desc.m99", "Return from subprogram." },

            { "diag.unclosed_comment", "Comment is missing the closing ')'" },
            { "diag.missing_value", "Address {0} is missing a value" },
            { "diag.invalid_number", "Invalid number \"{0}\"" },
            { "diag.unexpected_char", "Unexpected character \"{0}\"" },
            { "diag.unknown_address", "Unknown address letter {0}" },
            { "diag.unknown_g", "Unknown G-code G{0}" },
            { "diag.unknown_m", "Unknown M-code M{0}" },
            { "diag.arc_no_params", "Arc command is missing I/J/K or R" },
            { "diag.arc_missing_axis", "Arc is missing in-plane coordinates ({0} and {1})" },
            { "diag.arc_radius_invalid", "Arc radius is zero or invalid" },
            { "diag.arc_radius_mismatch", "R value does not match the centre-based radius (error {0:0.###}mm)" },
            { "diag.arc_no_endpoint", "Arc start and end coincide without full-circle parameters" },
            { "diag.feed_missing", "Cutting move G01/G02/G03 without feed rate F" },
            { "diag.feed_zero", "Feed rate F is zero" },
            { "diag.spindle_zero", "Spindle speed S is zero but cutting is programmed" },
            { "diag.spindle_not_started", "Cutting before the spindle is started (M03/M04 missing)" },
            { "diag.tool_missing", "T command used without M06 tool change" },
            { "diag.tool_out_of_library", "Tool T{0} is not in the tool library" },
            { "diag.diameter_exceeds_radius", "Tool diameter {0:0.###}mm exceeds arc diameter {1:0.###}mm" },
            { "diag.modal_conflict", "Conflicting commands {0} and {1} in the same block" },
            { "diag.cutter_comp_arc", "Arc with cutter compensation may gouge; please verify" },
            { "diag.rtcp_missing", "Rotary motion needs G43.4 tool tip following" },
            { "diag.soft_limit_x", "X over travel: {0:0.###} outside [{1:0.###}, {2:0.###}]" },
            { "diag.soft_limit_y", "Y over travel: {0:0.###} outside [{1:0.###}, {2:0.###}]" },
            { "diag.soft_limit_z", "Z over travel: {0:0.###} outside [{1:0.###}, {2:0.###}]" },
            { "diag.soft_limit_a", "A over travel: {0:0.###} outside [{1:0.###}, {2:0.###}]" },
            { "diag.soft_limit_b", "B over travel: {0:0.###} outside [{1:0.###}, {2:0.###}]" },
            { "diag.soft_limit_c", "C over travel: {0:0.###} outside [{1:0.###}, {2:0.###}]" },
            { "diag.outside_blank", "Path leaves the stock; air cutting possible" },
            { "diag.overcut", "Overcut: cutting {0:0.###}mm below the stock bottom" },
            { "diag.no_program_number", "Missing program number O" },
            { "diag.no_program_end", "Program has no M02/M30 end" },
            { "diag.canned_cycle_g80", "Canned cycle is not cancelled with G80" },
            { "diag.duplicate_same_line", "Command {0} appears twice in the same block" },
            { "diag.zero_position_move", "Move target equals current position; block can be removed" },
            { "diag.rapid_through_material", "Rapid move may pass through the stock" },
            { "diag.unknown_coordinate_system", "No work coordinate system selected (G54-G59)" },

            { "explain.empty", "Empty / comment line" },
            { "explain.prefix_rapid", "Rapid to " },
            { "explain.prefix_linear", "Line to " },
            { "explain.prefix_arc_cw", "Clockwise arc to " },
            { "explain.prefix_arc_ccw", "Counter-clockwise arc to " },
            { "explain.at_absolute", " (absolute)" },
            { "explain.at_incremental", " (incremental {0})" },
            { "explain.feed", ", feed {0:0.###}mm/min" },
            { "explain.feed_per_rev", ", feed {0:0.###}mm/rev" },
            { "explain.radius", ", radius {0:0.###}mm" },
            { "explain.plane", ", {0} plane" },
            { "explain.dwell", "Dwell {0:0.###} s" },
            { "explain.spindle_on_cw", "Spindle CW {0:0} rpm" },
            { "explain.spindle_on_ccw", "Spindle CCW {0:0} rpm" },
            { "explain.spindle_stop", "Spindle stop" },
            { "explain.coolant_on", "Coolant on" },
            { "explain.coolant_off", "Coolant off" },
            { "explain.tool_change", "Tool change to T{0}" },
            { "explain.tool_prepare", "Prepare tool T{0}" },
            { "explain.program_end", "Program end" },
            { "explain.program_stop", "Program stop" },
            { "explain.optional_stop", "Optional stop" },
            { "explain.cycle_enter", "Enter canned cycle {0}" },
            { "explain.cycle_cancel", "Cancel canned cycle" },
            { "explain.units", "Units changed to {0}" },
            { "explain.work_offset", "Select work offset {0}" },
            { "explain.rtcp_on", "Tool tip following on" },
            { "explain.rtcp_off", "Tool tip following off" },
            { "explain.no_motion", "No motion" },

            { "unit.mm", "millimetres" },
            { "unit.inch", "inches" },
            { "unit.mm_per_min", "mm/min" },
            { "unit.mm_per_rev", "mm/rev" },
            { "unit.rpm", "rpm" },
            { "unit.second", "s" },

            { "manual.category.motion", "Motion" },
            { "manual.category.plane_units", "Plane / units / distance" },
            { "manual.category.compensation", "Compensation" },
            { "manual.category.coordinates", "Coordinates & transforms" },
            { "manual.category.feed_spindle", "Feed & spindle" },
            { "manual.category.cycles", "Canned cycles" },
            { "manual.category.other_g", "Other G-codes" },
            { "manual.category.misc_m", "Miscellaneous M-codes" },

            { "ui.menu.file", "File" },
            { "ui.menu.new", "New" },
            { "ui.menu.open", "Open" },
            { "ui.menu.save", "Save" },
            { "ui.menu.save_as", "Save As" },
            { "ui.menu.import", "Import" },
            { "ui.menu.export", "Export" },
            { "ui.menu.share", "Share" },
            { "ui.menu.recent", "Recent files" },
            { "ui.menu.undo", "Undo" },
            { "ui.menu.redo", "Redo" },
            { "ui.menu.find", "Find" },
            { "ui.menu.replace", "Replace" },
            { "ui.menu.simulate", "Simulate" },
            { "ui.tab.simulation", "Simulation" },
            { "ui.tab.tools", "Tools" },
            { "ui.tab.blank", "Stock" },
            { "ui.tab.manual", "Reference" },
            { "ui.view.top", "Top" },
            { "ui.view.front", "Front" },
            { "ui.view.side", "Side" },
            { "ui.view.iso", "Isometric" },
            { "ui.blank.box", "Box" },
            { "ui.blank.cylinder", "Cylinder" },
            { "ui.blank.custom", "Custom" },
            { "ui.tool.flat", "Flat end mill" },
            { "ui.tool.ball", "Ball end mill" },
            { "ui.tool.bull", "Bull nose" },
            { "ui.tool.drill", "Drill" },
            { "ui.tool.tap", "Tap" },
            { "ui.tool.chamfer", "Chamfer mill" },
            { "ui.tool.thread", "Thread mill" },
            { "ui.tool.probe", "Probe" },
            { "ui.machine.3axis", "3-axis vertical" },
            { "ui.machine.4axis", "4-axis" },
            { "ui.machine.5axis", "5-axis" },
            { "ui.scene.trajectory", "Tool path" },
            { "ui.scene.machine", "Machine" },
            { "ui.scene.workpiece", "Workpiece" },
            { "ui.scene.fixture", "Fixture" },
            { "ui.scene.axes", "Axes" },
            { "ui.scene.grid", "Grid" },
            { "ui.scene.section", "Section" },
            { "ui.theme.dark", "Dark theme" },
            { "ui.theme.light", "Light theme" },

            { "opt.redundant_rapid", "Zero-length rapid moves found; removing them shortens air cutting" },
            { "opt.feed_variation", "Feed varies from {0:0.###} to {1:0.###} mm/min ({2:0.##}x); consider unifying it" },
            { "opt.deep_plunge", "Deep vertical plunges detected; pre-drill or use ramping/pecking" },
            { "opt.rapid_low", "Rapid moves at low Z are a crash risk; raise the clearance plane" },
            { "opt.tool_order", "{0} repeated tool changes; group operations that share a tool" },
            { "opt.back_forth", "Back-and-forth air moves found; reorder the path" },

            { "collision.toolworkpiece", "Line {0}: tool collides with the workpiece (depth {1:0.###}mm)" },
            { "collision.toolfixture", "Line {0}: tool collides with the fixture (depth {1:0.###}mm)" },
            { "collision.toolmachine", "Line {0}: tool collides with the machine (depth {1:0.###}mm)" },
            { "collision.holderworkpiece", "Line {0}: holder collides with the workpiece (depth {1:0.###}mm)" },
            { "collision.holderfixture", "Line {0}: holder collides with the fixture (depth {1:0.###}mm)" },
            { "collision.holdermachine", "Line {0}: holder collides with the machine (depth {1:0.###}mm)" },
            { "collision.rapidthroughmaterial", "Line {0}: rapid move passes through the stock" },

            { "material.aluminum", "Aluminium" },
            { "material.steel_1045", "Steel 1045" },
            { "material.stainless_304", "Stainless 304" },
            { "material.brass", "Brass" },
            { "material.copper", "Copper" },
            { "material.cast_iron", "Cast iron" },
            { "material.titanium", "Titanium" },
            { "material.plastic_abs", "ABS plastic" },
            { "material.wood", "Wood" },

            // ---- Recording / import / project ui.* ----
            { "ui.record.start", "Start recording" },
            { "ui.record.stop", "Stop recording" },
            { "ui.record.replay", "Replay" },
            { "ui.record.pause", "Pause replay" },
            { "ui.record.save", "Save recording" },
            { "ui.record.load", "Load recording" },
            { "ui.import.model", "Import model" },
            { "ui.import.stl", "Import STL model" },
            { "ui.import.step", "Import STEP model" },
            { "ui.import.gltf_fbx", "Import glTF/FBX model" },
            { "ui.import.machine_fixture", "Import machine/fixture model" },
            { "ui.capture.screenshot", "Save screenshot" },
            { "ui.capture.video", "Export simulation video" },
            { "ui.project.manager", "Project manager" },
            { "ui.project.new", "New project" },
            { "ui.project.duplicate", "Duplicate project" },
            { "ui.project.delete", "Delete project" },
            { "ui.project.rename", "Rename project" },

            // ---- Main UI skeleton ----
            { "ui.app.title", "CNC Machining Simulator" },
            { "ui.tab.file", "File" },
            { "ui.tab.analysis", "Analysis" },
            { "ui.tab.scene", "Scene" },
            { "ui.tab.media", "Media" },
            { "ui.tab.project", "Projects" },
            { "ui.tab.tutorial", "Tutorials" },
            { "ui.machine.custom", "Custom machine" },
            { "ui.view.fit", "Fit view" },
            { "ui.view.back", "Back" },
            { "ui.view.bottom", "Bottom" },
            { "ui.view.orbit_hint", "LMB orbit · RMB pan · wheel zoom" },

            // ---- Playback ----
            { "ui.ctrl.play", "Play/Pause" },
            { "ui.ctrl.stop", "Stop" },
            { "ui.ctrl.step_fwd", "Step forward" },
            { "ui.ctrl.step_back", "Step back" },
            { "ui.ctrl.restart", "Restart" },
            { "ui.ctrl.speed", "Speed" },
            { "ui.ctrl.progress", "Progress" },

            // ---- Simulation status ----
            { "ui.status.idle", "Ready" },
            { "ui.status.running", "Simulating…" },
            { "ui.status.paused", "Paused" },
            { "ui.status.stopped", "Stopped" },
            { "ui.status.finished", "Simulation finished" },
            { "ui.status.theme_toggled", "Theme switched" },
            { "ui.status.saved", "Saved" },
            { "ui.status.open_failed", "Open failed" },
            { "ui.status.no_program", "Open or enter G-code first" },
            { "ui.status.recording", "Recording…" },
            { "ui.status.replaying", "Replaying…" },

            // ---- File panel ----
            { "ui.file.new", "New" },
            { "ui.file.clear", "Clear" },
            { "ui.file.recent", "Recent files" },
            { "ui.file.recover", "Recovered sessions" },
            { "ui.file.export", "Export to file…" },
            { "ui.file.font_size", "Font size" },
            { "ui.file.wrap", "Word wrap" },
            { "ui.file.diagnostics", "Diagnostics" },

            // ---- Simulation panel ----
            { "ui.sim.controls", "Playback" },
            { "ui.sim.progress", "Progress" },
            { "ui.sim.live_removal", "Live material removal" },
            { "ui.sim.trajectory", "Show toolpath" },
            { "ui.sim.rapid", "Show rapid moves" },
            { "ui.sim.cutting", "Show cutting" },
            { "ui.sim.style", "Toolpath style" },
            { "ui.sim.style.lines", "Lines" },
            { "ui.sim.style.solid", "Solid" },
            { "ui.sim.quality", "Quality" },
            { "ui.sim.quality.low", "Low" },
            { "ui.sim.quality.medium", "Medium" },
            { "ui.sim.quality.high", "High" },

            // ---- Tools panel ----
            { "ui.tools.list", "Tool list" },
            { "ui.tools.add", "Add tool" },
            { "ui.tools.remove", "Remove" },
            { "ui.tools.type", "Type" },
            { "ui.tools.number", "Number" },
            { "ui.tools.diameter", "Diameter (mm)" },
            { "ui.tools.corner", "Corner radius (mm)" },
            { "ui.tools.flute", "Flute length (mm)" },
            { "ui.tools.stickout", "Stick-out (mm)" },
            { "ui.tools.selected", "Current tool" },

            // ---- Blank panel ----
            { "ui.blank.shape", "Shape" },
            { "ui.blank.size_x", "X size (mm)" },
            { "ui.blank.size_y", "Y size (mm)" },
            { "ui.blank.size_z", "Z size (mm)" },
            { "ui.blank.material", "Material" },
            { "ui.blank.offset", "Work offset" },
            { "ui.blank.fixture", "Enable fixture" },
            { "ui.blank.touch", "Three-point touch-off" },

            // ---- Analysis panel ----
            { "ui.analysis.run", "Re-analyze" },
            { "ui.analysis.time", "Machining time" },
            { "ui.analysis.collision", "Collision check" },
            { "ui.analysis.machining", "Gouge/undercut" },
            { "ui.analysis.optimize", "Path optimization" },
            { "ui.analysis.params", "Recommended parameters" },
            { "ui.analysis.none", "None" },
            { "ui.analysis.runtime", "Runtime" },
            { "ui.analysis.total", "Total" },

            // ---- Scene panel ----
            { "ui.scene.show_grid", "Show grid" },
            { "ui.scene.show_axes", "Show axes" },
            { "ui.scene.show_machine", "Show machine" },
            { "ui.scene.show_workpiece", "Show workpiece" },
            { "ui.scene.show_fixture", "Show fixture" },
            { "ui.scene.section_enable", "Enable section" },
            { "ui.scene.section_axis", "Section axis" },
            { "ui.scene.section_offset", "Section offset" },
            { "ui.scene.opacity", "Opacity" },
            { "ui.scene.measure", "Measure tool" },
            { "ui.scene.measure.none", "Off" },
            { "ui.scene.measure.distance", "Distance" },
            { "ui.scene.measure.angle", "Angle" },
            { "ui.scene.measure.clear", "Clear measurement" },

            // ---- Media panel ----
            { "ui.media.screenshot", "Screenshot" },
            { "ui.media.video_record", "Record frame sequence" },
            { "ui.media.video_stop", "Stop recording" },
            { "ui.media.sim_start", "Start sim recording" },
            { "ui.media.sim_stop", "Stop sim recording" },
            { "ui.media.sim_replay", "Replay" },
            { "ui.media.sim_save", "Save recording" },
            { "ui.media.sim_load", "Load recording" },

            // ---- Code editor ----
            { "ui.editor.toggle", "Code editor" },
            { "ui.editor.shown", "Code editor opened" },
            { "ui.editor.hidden", "Code editor closed" },
            { "ui.editor.placeholder", "Select a line, then edit here" },
            { "ui.editor.apply", "Apply" },

            // ---- Project panel ----
            { "ui.project.name", "Project name" },
            { "ui.project.create", "New project" },
            { "ui.project.save", "Save to project" },
            { "ui.project.load", "Load project" },
            { "ui.project.empty", "No projects yet" },

            // ---- Tutorial panel ----
            { "ui.tutorial.list", "Tutorials" },
            { "ui.tutorial.start", "Start" },
            { "ui.tutorial.next", "Next" },
            { "ui.tutorial.prev", "Previous" },
            { "ui.tutorial.finish", "Finish" },

            // ---- Manual panel ----
            { "ui.manual.search", "Search G/M codes" },
            { "ui.manual.g", "G codes" },
            { "ui.manual.m", "M codes" },

            { "diag.import.unsupported", "Unsupported model format: {0}" },
            { "diag.import.requires_unity", "This format must be imported in Unity (glTF/FBX/STEP)" },
            { "diag.import.failed", "Model import failed: {0}" },

            // ---- Tutorials tutorial.* ----
            { "tutorial.getting_started.title", "Getting started" },
            { "tutorial.getting_started.desc", "Full flow from opening a program to running a simulation" },
            { "tutorial.gs.s1.title", "Welcome to CNC simulation" },
            { "tutorial.gs.s1.body", "This tour walks you through a complete machining simulation. Click Next to continue." },
            { "tutorial.gs.s2.title", "Open G-code" },
            { "tutorial.gs.s2.body", "Paste or open a .nc / .tap program in the code editor; syntax errors are flagged live." },
            { "tutorial.gs.s3.title", "Try opening a file" },
            { "tutorial.gs.s3.body", "Click the Open button to load a sample program." },
            { "tutorial.gs.s4.title", "Run the simulation" },
            { "tutorial.gs.s4.body", "Click Simulate to watch the tool follow the program segment by segment." },
            { "tutorial.gs.s5.title", "Inspect the result" },
            { "tutorial.gs.s5.body", "Orbit and zoom in the 3D view to inspect the machined workpiece." },

            { "tutorial.simulation.title", "Simulation and material removal" },
            { "tutorial.simulation.desc", "Set up tools and stock, then control playback" },
            { "tutorial.sim.s1.title", "Pick a tool" },
            { "tutorial.sim.s1.body", "Choose the tool type and diameter in the tool panel; removal uses its true shape." },
            { "tutorial.sim.s2.title", "Define the stock" },
            { "tutorial.sim.s2.body", "Set the stock size and material; cutting parameters are estimated from them." },
            { "tutorial.sim.s3.title", "Playback controls" },
            { "tutorial.sim.s3.body", "Play, pause, step and scrub the timeline to check the program segment by segment." },
            { "tutorial.sim.s4.title", "Adjust speed" },
            { "tutorial.sim.s4.body", "Drag the speed slider to speed up preview without affecting the time estimate." },
            { "tutorial.sim.s5.title", "Timeline" },
            { "tutorial.sim.s5.body", "The timeline shows rapid and cutting segments, so you can jump to any moment." },

            { "tutorial.fiveaxis.title", "Five-axis simulation" },
            { "tutorial.fiveaxis.desc", "Configure multi-axis machines and tool tip following" },
            { "tutorial.5x.s1.title", "Choose a machine" },
            { "tutorial.5x.s1.body", "Pick a 4-axis or 5-axis configuration in the machine selector." },
            { "tutorial.5x.s2.title", "Kinematics" },
            { "tutorial.5x.s2.body", "Table-Table, Head-Table and Head-Head structures are supported; the tip position is solved automatically." },
            { "tutorial.5x.s3.title", "Enable RTCP" },
            { "tutorial.5x.s3.body", "With RTCP on, programmed coordinates are tool tip coordinates and rotation is compensated automatically." },
        };
    }
}
